version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: gamerdou
      MONGO_INITDB_ROOT_USERNAME: gamerdou_username
      MONGO_INITDB_ROOT_PASSWORD: gamerdou_password
    volumes:
      - ./db/mongodb:/data/db
    ports:
      - 27017:27017

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: gamerdou
      POSTGRES_USER: gamerdou_username
      POSTGRES_PASSWORD: gamerdou_password
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432